# Generated by Django 5.2.6 on 2025-09-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('gym', 'باشگاهی'), ('platform', 'پلتفرم')], default='gym', max_length=100),
        ),
    ]
