# Generated by Django 5.2.6 on 2025-10-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_announcement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sent_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('gym', 'باشگاهی'), ('platform_all', 'پلتفرم به همه'), ('platform_gym', 'پلتفرم به باشگاه'), ('platform_customer', 'پلتفرم به کاربر')], default='gym', max_length=100),
        ),
    ]
