# Generated by Django 5.2.6 on 2025-10-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_notification_sent_sms_notification_sms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='meta',
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
