# Generated by Django 5.2.6 on 2025-10-14 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_commission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payer_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payer_transactions', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payer_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_transactions', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('online', 'آنلاین'), ('cash', 'نقدی')], default='online', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
