# Generated by Django 5.2.6 on 2025-09-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_for_club_per_month', models.IntegerField(default=0)),
                ('commission_for_club_per_day', models.IntegerField(default=0)),
                ('commission_for_marketer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('announcements', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
