# Generated by Django 5.2.6 on 2025-09-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_gender_alter_customer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], default='male', max_length=255),
        ),
    ]
