# Generated by Django 5.2.6 on 2025-10-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customers/profile-photos/'),
        ),
    ]
