# Generated by Django 5.2.6 on 2025-10-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymmanager',
            name='balance',
        ),
    ]
