# Generated by Django 5.2.6 on 2025-10-16 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymSecretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(blank=True, max_length=50, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_secretary', to='accounts.gymmanager')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gym_secretary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
