# Generated by Django 5.2.6 on 2025-10-16 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_gymsecretary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymSecretary',
        ),
    ]
