# Generated by Django 5.2.6 on 2025-09-21 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('main_img', models.ImageField(upload_to='gym_img/main_imgs')),
                ('phone', models.CharField(max_length=50)),
                ('headline_phone', models.CharField(max_length=50)),
                ('commission_type', models.CharField(choices=[('customer', 'مشتری'), ('gym', 'باشگاه')], max_length=50)),
                ('facilities', models.CharField(max_length=5000)),
                ('description', models.TextField()),
                ('work_hours_per_day', models.CharField(max_length=500)),
                ('work_days_per_week', models.CharField(max_length=500)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to='accounts.gymmanager')),
            ],
        ),
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('status', models.CharField(default='available', max_length=50)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closets', to='gyms.gym')),
            ],
        ),
        migrations.CreateModel(
            name='BlockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_gyms', to='accounts.customer')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='gyms.gym')),
            ],
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('session_left', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('days', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.customer')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gyms.gym')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='payments.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='InOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('confirm_in', models.BooleanField(default=False)),
                ('closet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gyms.closet')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inouts', to='accounts.customer')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inouts', to='gyms.gym')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gyms.membership')),
            ],
        ),
        migrations.CreateModel(
            name='MemberShipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('days', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('gyms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_types', to='gyms.gym')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gyms.membershiptype'),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='accounts.customer')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='gyms.gym')),
            ],
        ),
    ]
