# Generated by Django 5.2.6 on 2025-09-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='gender',
            field=models.CharField(choices=[('both', 'زنانه و مردانه'), ('female', 'زنانه'), ('male', 'مردانه')], default='male', max_length=50),
        ),
    ]
