# Generated by Django 5.2.6 on 2025-09-26 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_gym_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='gyms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_types', to='gyms.gym'),
        ),
    ]
