# Generated by Django 5.2.6 on 2025-09-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_alter_membershiptype_gyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='inout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
