# Generated by Django 5.2.6 on 2025-10-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_gymbanner_gymimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gymbanner',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
