# Generated by Django 5.2.6 on 2025-10-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_gym_is_active_gymbanner_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
