# Generated by Django 5.2.6 on 2025-10-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_membership_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='type',
            field=models.CharField(choices=[('daily', 'روزانه'), ('monthly', 'ماهانه')], default='monthly', max_length=255),
        ),
    ]
