# Generated by Django 5.2.6 on 2025-10-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_membershiptype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='status',
            field=models.CharField(choices=[('available', 'در دسترس'), ('unavailable', 'غیرقابل دسترس')], default='available', max_length=50),
        ),
    ]
