# Generated by Django 5.2.6 on 2025-10-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0009_alter_closet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='gymbanner',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('gym',), name='unique_main_banner_per_gym'),
        ),
    ]
