# Generated by Django 5.2.6 on 2025-10-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0011_gymsecretary'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='notified_expiration',
            field=models.BooleanField(default=False),
        ),
    ]
